### ISSUE TITLE
Sparse polynomials require std, but may be made no_std compatible

### ISSUE THREAD

**Issue by cargodog** [cargodog/polynomials#29]
After looking deeper into @drewstone's provided implementation for sparse polynomials (thanks @drewstone!), I wonder if it could be rewritten without the dependency on BTreeMaps. This is the only dependency from std, but I'm not convinced its necessary.

## How sparse polynomial's work today:
Each sparse polynomial is implemented as a vector of `(u64, T)` tuples. The implemented math traits then convert this vector into a BTreeMap and perform the associated math using key-value lookups in the BTree.

## Improvement:
All of the math (at least as I have seen so far) could be done by iterating over a vector instead of a map. In-fact, every operation (add, subtract, evaluate, ...) requires use of every coefficient in the polynomial. Therefore, performing key-value lookups for each coefficient is actually slower than just iterating the vector of coefficients.

**Comment by cargodog** [comment]
@drewstone am I missing some reason why BTreeMaps are necessary or beneficial?

On a slightly unrelated note, if we reduce this back down to vector operations only, I would prefer to remove my original polynomial implementation and replace it outright with sparse polynomials. They be much more efficient for high order polynomials and only less efficient for high order polynomials that have very few zeros. I think that case would be rare though, as most high order polynomials will have many zeros. Low order polynomials likely wouldn't notice the difference.

**Comment by drewstone** [comment]
The BTreeMap implementation that I'm using is no_std compatible actually! It stands for "substrate primitives"_std => `sp_std`. It is just one of the only libraries I'm familiar with that supports a map data structure that is no_std.

If there's a more efficient way to do arithmetic using vecs then this would be worth investigating, I haven't given it much thought and chose this route as it was simpler to write and think about.

**Comment by cargodog** [comment]
> I do know that sp_std is no-std compatible for sure though.

Ah, that's good to know!

> If there's a more efficient way to do arithmetic using vecs then this would be worth investigating

I will think on it a little bit. If its a lot of trouble and the benefit is small, then I won't waste too much time on it.
